@file:Suppress("unused")

package azagroup.kotlin.css

// CSS Reference
// http://www.w3schools.com/cssref/default.asp


// Color Properties
var Stylesheet.color by ColorPropertyHandler("color")
var Stylesheet.opacity by PropertyHandler("opacity")

// Background and Border Properties
var Stylesheet.background by PropertyHandler("background")
var Stylesheet.backgroundAttachment by PropertyHandler("background-attachment")
var Stylesheet.backgroundBlendMode by PropertyHandler("background-blend-mode")
var Stylesheet.backgroundColor by ColorPropertyHandler("background-color")
var Stylesheet.backgroundImage by PropertyHandler("background-image")
var Stylesheet.backgroundPosition by PropertyHandler("background-position")
var Stylesheet.backgroundRepeat by PropertyHandler("background-repeat")
var Stylesheet.backgroundClip by PropertyHandler("background-clip")
var Stylesheet.backgroundOrigin by PropertyHandler("background-origin")
var Stylesheet.backgroundSize by PropertyHandler("background-size")
var Stylesheet.border by PropertyHandler("border")
var Stylesheet.borderBottom by PropertyHandler("border-bottom")
var Stylesheet.borderBottomColor by ColorPropertyHandler("border-bottom-color")
var Stylesheet.borderBottomLeftRadius by PropertyHandler("border-bottom-left-radius")
var Stylesheet.borderBottomRightRadius by PropertyHandler("border-bottom-right-radius")
var Stylesheet.borderBottomStyle by PropertyHandler("border-bottom-style")
var Stylesheet.borderBottomWidth by PropertyHandler("border-bottom-width")
var Stylesheet.borderColor by ColorPropertyHandler("border-color")
var Stylesheet.borderImage by PropertyHandler("border-image")
var Stylesheet.borderImageOutset by PropertyHandler("border-image-outset")
var Stylesheet.borderImageRepeat by PropertyHandler("border-image-repeat")
var Stylesheet.borderImageSlice by PropertyHandler("border-image-slice")
var Stylesheet.borderImageSource by PropertyHandler("border-image-source")
var Stylesheet.borderImageWidth by PropertyHandler("border-image-width")
var Stylesheet.borderLeft by PropertyHandler("border-left")
var Stylesheet.borderLeftColor by ColorPropertyHandler("border-left-color")
var Stylesheet.borderLeftStyle by PropertyHandler("border-left-style")
var Stylesheet.borderLeftWidth by PropertyHandler("border-left-width")
var Stylesheet.borderRadius by PropertyHandler("border-radius")
var Stylesheet.borderRight by PropertyHandler("border-right")
var Stylesheet.borderRightColor by ColorPropertyHandler("border-right-color")
var Stylesheet.borderRightStyle by PropertyHandler("border-right-style")
var Stylesheet.borderRightWidth by PropertyHandler("border-right-width")
var Stylesheet.borderStyle by PropertyHandler("border-style")
var Stylesheet.borderTop by PropertyHandler("border-top")
var Stylesheet.borderTopColor by ColorPropertyHandler("border-top-color")
var Stylesheet.borderTopLeftRadius by PropertyHandler("border-top-left-radius")
var Stylesheet.borderTopRightRadius by PropertyHandler("border-top-right-radius")
var Stylesheet.borderTopStyle by PropertyHandler("border-top-style")
var Stylesheet.borderTopWidth by PropertyHandler("border-top-width")
var Stylesheet.borderWidth by PropertyHandler("border-width")
var Stylesheet.boxDecorationBreak by PropertyHandler("box-decoration-break")
var Stylesheet.boxShadow by PropertyHandler("box-shadow")

// Basic Box Properties
var Stylesheet.bottom by PropertyHandler("bottom")
var Stylesheet.clear by PropertyHandler("clear")
var Stylesheet.clip by PropertyHandler("clip")
var Stylesheet.display by PropertyHandler("display")
var Stylesheet.float by PropertyHandler("float")
var Stylesheet.height by PropertyHandler("height")
var Stylesheet.left by PropertyHandler("left")
var Stylesheet.margin by PropertyHandler("margin")
var Stylesheet.marginBottom by PropertyHandler("margin-bottom")
var Stylesheet.marginLeft by PropertyHandler("margin-left")
var Stylesheet.marginRight by PropertyHandler("margin-right")
var Stylesheet.marginTop by PropertyHandler("margin-top")
var Stylesheet.maxHeight by PropertyHandler("max-height")
var Stylesheet.maxWidth by PropertyHandler("max-width")
var Stylesheet.minHeight by PropertyHandler("min-height")
var Stylesheet.minWidth by PropertyHandler("min-width")
var Stylesheet.overflow by PropertyHandler("overflow")
var Stylesheet.overflowX by PropertyHandler("overflow-x")
var Stylesheet.overflowY by PropertyHandler("overflow-y")
var Stylesheet.padding by PropertyHandler("padding")
var Stylesheet.paddingBottom by PropertyHandler("padding-bottom")
var Stylesheet.paddingLeft by PropertyHandler("padding-left")
var Stylesheet.paddingRight by PropertyHandler("padding-right")
var Stylesheet.paddingTop by PropertyHandler("padding-top")
var Stylesheet.position by PropertyHandler("position")
var Stylesheet.right by PropertyHandler("right")
var Stylesheet.top by PropertyHandler("top")
var Stylesheet.visibility by PropertyHandler("visibility")
var Stylesheet.width by PropertyHandler("width")
var Stylesheet.verticalAlign by PropertyHandler("vertical-align")
var Stylesheet.zIndex by PropertyHandler("z-index")

// Flexible Box Layout
var Stylesheet.alignContent by PropertyHandler("align-content")
var Stylesheet.alignItems by PropertyHandler("align-items")
var Stylesheet.alignSelf by PropertyHandler("align-self")
var Stylesheet.flex by PropertyHandler("flex")
var Stylesheet.flexBasis by PropertyHandler("flex-basis")
var Stylesheet.flexDirection by PropertyHandler("flex-direction")
var Stylesheet.flexFlow by PropertyHandler("flex-flow")
var Stylesheet.flexGrow by PropertyHandler("flex-grow")
var Stylesheet.flexShrink by PropertyHandler("flex-shrink")
var Stylesheet.flexWrap by PropertyHandler("flex-wrap")
var Stylesheet.justifyContent by PropertyHandler("justify-content")
var Stylesheet.order by PropertyHandler("order")

// Text Properties
var Stylesheet.hangingPunctuation by PropertyHandler("hanging-punctuation")
var Stylesheet.hyphens by PropertyHandler("hyphens")
var Stylesheet.letterSpacing by PropertyHandler("letter-spacing")
var Stylesheet.lineBreak by PropertyHandler("line-break")
var Stylesheet.lineHeight by PropertyHandler("line-height")
var Stylesheet.overflowWrap by PropertyHandler("overflow-wrap")
var Stylesheet.tabSize by PropertyHandler("tab-size")
var Stylesheet.textAlign by PropertyHandler("text-align")
var Stylesheet.textAlignLast by PropertyHandler("text-align-last")
var Stylesheet.textIndent by PropertyHandler("text-indent")
var Stylesheet.textJustify by PropertyHandler("text-justify")
var Stylesheet.textTransform by PropertyHandler("text-transform")
var Stylesheet.whiteSpace by PropertyHandler("white-space")
var Stylesheet.wordBreak by PropertyHandler("word-break")
var Stylesheet.wordSpacing by PropertyHandler("word-spacing")
var Stylesheet.wordWrap by PropertyHandler("word-wrap")

// Text Decoration Properties
var Stylesheet.textDecoration by PropertyHandler("text-decoration")
var Stylesheet.textDecorationColor by ColorPropertyHandler("text-decoration-color")
var Stylesheet.textDecorationLine by PropertyHandler("text-decoration-line")
var Stylesheet.textDecorationStyle by PropertyHandler("text-decoration-style")
var Stylesheet.textShadow by PropertyHandler("text-shadow")
var Stylesheet.textUnderlinePosition by PropertyHandler("text-underline-position")

// Font Properties
var Stylesheet.font by PropertyHandler("font")
var Stylesheet.fontFamily by PropertyHandler("font-family")
var Stylesheet.fontFeatureSettings by PropertyHandler("font-feature-settings")
var Stylesheet.fontKerning by PropertyHandler("font-kerning")
var Stylesheet.fontLanguageOverride by PropertyHandler("font-language-override")
var Stylesheet.fontSize by PropertyHandler("font-size")
var Stylesheet.fontSizeAdjust by PropertyHandler("font-size-adjust")
var Stylesheet.fontStretch by PropertyHandler("font-stretch")
var Stylesheet.fontStyle by PropertyHandler("font-style")
var Stylesheet.fontSynthesis by PropertyHandler("font-synthesis")
var Stylesheet.fontVariant by PropertyHandler("font-variant")
var Stylesheet.fontVariantAlternates by PropertyHandler("font-variant-alternates")
var Stylesheet.fontVariantCaps by PropertyHandler("font-variant-caps")
var Stylesheet.fontVariantEastAsian by PropertyHandler("font-variant-east-asian")
var Stylesheet.fontVariantLigatures by PropertyHandler("font-variant-ligatures")
var Stylesheet.fontVariantNumeric by PropertyHandler("font-variant-numeric")
var Stylesheet.fontVariantPosition by PropertyHandler("font-variant-position")
var Stylesheet.fontWeight by PropertyHandler("font-weight")

// Writing Modes Properties
var Stylesheet.direction by PropertyHandler("direction")
var Stylesheet.textOrientation by PropertyHandler("text-orientation")
var Stylesheet.textCombineUpright by PropertyHandler("text-combine-upright")
var Stylesheet.unicodeBidi by PropertyHandler("unicode-bidi")
var Stylesheet.writingMode by PropertyHandler("writing-mode")

// Table Properties
var Stylesheet.borderCollapse by PropertyHandler("border-collapse")
var Stylesheet.borderSpacing by PropertyHandler("border-spacing")
var Stylesheet.captionSide by PropertyHandler("caption-side")
var Stylesheet.emptyCells by PropertyHandler("empty-cells")
var Stylesheet.tableLayout by PropertyHandler("table-layout")

// Lists and Counters Properties
var Stylesheet.counterIncrement by PropertyHandler("counter-increment")
var Stylesheet.counterReset by PropertyHandler("counter-reset")
var Stylesheet.listStyle by PropertyHandler("list-style")
var Stylesheet.listStyleImage by PropertyHandler("list-style-image")
var Stylesheet.listStylePosition by PropertyHandler("list-style-position")
var Stylesheet.listStyleType by PropertyHandler("list-style-type")

// Animation Properties
var Stylesheet.animation by PropertyHandler("animation")
var Stylesheet.animationDelay by PropertyHandler("animation-delay")
var Stylesheet.animationDirection by PropertyHandler("animation-direction")
var Stylesheet.animationDuration by PropertyHandler("animation-duration")
var Stylesheet.animationFillMode by PropertyHandler("animation-fill-mode")
var Stylesheet.animationIterationCount by PropertyHandler("animation-iteration-count")
var Stylesheet.animationName by PropertyHandler("animation-name")
var Stylesheet.animationPlayState by PropertyHandler("animation-play-state")
var Stylesheet.animationTimingFunction by PropertyHandler("animation-timing-function")

// Transform Properties
var Stylesheet.backfaceVisibility by PropertyHandler("backface-visibility")
var Stylesheet.perspective by PropertyHandler("perspective")
var Stylesheet.perspectiveOrigin by PropertyHandler("perspective-origin")
var Stylesheet.transform by PropertyHandler("transform")
var Stylesheet.transformOrigin by PropertyHandler("transform-origin")
var Stylesheet.transformStyle by PropertyHandler("transform-style")

// Transitions Properties
var Stylesheet.transition by PropertyHandler("transition")
var Stylesheet.transitionProperty by PropertyHandler("transition-property")
var Stylesheet.transitionDuration by PropertyHandler("transition-duration")
var Stylesheet.transitionTimingFunction by PropertyHandler("transition-timing-function")
var Stylesheet.transitionDelay by PropertyHandler("transition-delay")

// Basic User Interface Properties
var Stylesheet.boxSizing by PropertyHandler("box-sizing")
var Stylesheet.content by ContentPropertyHandler("content")
var Stylesheet.cursor by PropertyHandler("cursor")
var Stylesheet.imeMode by PropertyHandler("ime-mode")
var Stylesheet.navDown by PropertyHandler("nav-down")
var Stylesheet.navIndex by PropertyHandler("nav-index")
var Stylesheet.navLeft by PropertyHandler("nav-left")
var Stylesheet.navRight by PropertyHandler("nav-right")
var Stylesheet.navUp by PropertyHandler("nav-up")
var Stylesheet.outline by PropertyHandler("outline")
var Stylesheet.outlineColor by ColorPropertyHandler("outline-color")
var Stylesheet.outlineOffset by PropertyHandler("outline-offset")
var Stylesheet.outlineStyle by PropertyHandler("outline-style")
var Stylesheet.outlineWidth by PropertyHandler("outline-width")
var Stylesheet.resize by PropertyHandler("resize")
var Stylesheet.textOverflow by PropertyHandler("text-overflow")

// Multi-column Layout Properties
var Stylesheet.breakAfter by PropertyHandler("break-after")
var Stylesheet.breakBefore by PropertyHandler("break-before")
var Stylesheet.breakInside by PropertyHandler("break-inside")
var Stylesheet.columnCount by PropertyHandler("column-count")
var Stylesheet.columnFill by PropertyHandler("column-fill")
var Stylesheet.columnGap by PropertyHandler("column-gap")
var Stylesheet.columnRule by PropertyHandler("column-rule")
var Stylesheet.columnRuleColor by ColorPropertyHandler("column-rule-color")
var Stylesheet.columnRuleStyle by PropertyHandler("column-rule-style")
var Stylesheet.columnRuleWidth by PropertyHandler("column-rule-width")
var Stylesheet.columnSpan by PropertyHandler("column-span")
var Stylesheet.columnWidth by PropertyHandler("column-width")
var Stylesheet.columns by PropertyHandler("columns")
var Stylesheet.widows by PropertyHandler("widows")

// Paged Media
var Stylesheet.orphans by PropertyHandler("orphans")
var Stylesheet.pageBreakAfter by PropertyHandler("page-break-after")
var Stylesheet.pageBreakBefore by PropertyHandler("page-break-before")
var Stylesheet.pageBreakInside by PropertyHandler("page-break-inside")

// Generated Content for Paged Media
var Stylesheet.marks by PropertyHandler("marks")
var Stylesheet.quotes by PropertyHandler("quotes")

// Filter Effects Properties
var Stylesheet.filter by PropertyHandler("filter")

// Image Values and Replaced Content
var Stylesheet.imageOrientation by PropertyHandler("image-orientation")
var Stylesheet.imageRendering by PropertyHandler("image-rendering")
var Stylesheet.imageResolution by PropertyHandler("image-resolution")
var Stylesheet.objectFit by PropertyHandler("object-fit")
var Stylesheet.objectPosition by PropertyHandler("object-position")

// Masking Properties
var Stylesheet.mask by PropertyHandler("mask")
var Stylesheet.maskType by PropertyHandler("mask-type")

// Speech Properties
var Stylesheet.mark by PropertyHandler("mark")
var Stylesheet.markAfter by PropertyHandler("mark-after")
var Stylesheet.markBefore by PropertyHandler("mark-before")
var Stylesheet.phonemes by PropertyHandler("phonemes")
var Stylesheet.rest by PropertyHandler("rest")
var Stylesheet.restAfter by PropertyHandler("rest-after")
var Stylesheet.restBefore by PropertyHandler("rest-before")
var Stylesheet.voiceBalance by PropertyHandler("voice-balance")
var Stylesheet.voiceDuration by PropertyHandler("voice-duration")
var Stylesheet.voicePitch by PropertyHandler("voice-pitch")
var Stylesheet.voicePitchRange by PropertyHandler("voice-pitch-range")
var Stylesheet.voiceRate by PropertyHandler("voice-rate")
var Stylesheet.voiceStress by PropertyHandler("voice-stress")
var Stylesheet.voiceVolume by PropertyHandler("voice-volume")

// Marquee Properties
var Stylesheet.marqueeDirection by PropertyHandler("marquee-direction")
var Stylesheet.marqueePlayCount by PropertyHandler("marquee-play-count")
var Stylesheet.marqueeSpeed by PropertyHandler("marquee-speed")
var Stylesheet.marqueeStyle by PropertyHandler("marquee-style")

// Exotic
var Stylesheet.zoom by PropertyHandler("zoom")
var Stylesheet.src by PropertyHandler("src") // @font-face
